""" Module for daily post agent. """

from utils.openai import OpenAIClient

class DailyPostAgent:
    """ Agent for generating daily post."""

    def __init__(self):
        """Initializes the DailyPostAgent."""
        self.openai = OpenAIClient()

    def generate_post(self) -> str:
        """Generates a daily post for software developers in Nigeria.

        Returns:
            str: The generated daily post.
        """
        return self.openai.chat("""
                                Your task is to write a short motivational post for software developers in Nigeria. Under "280 characters". Suitable for Twitter.
                                It must end with a call to action.
                                Don't be overly excited about the topic, but be enthusiastic about the subject.
                                Don't be too formal, but be friendly.
                                Don't use figures of speech.
                                Use active voice.
                                Use a bit of Nigeria pidgin English.
                                Write in the first person. Use the story telling technique implored in the examples below.

                                Example:
                                1. "Hey Naija dev, I know things are tough, I know you are tired of Garri and unreliable power supply, but remember things go soft very soon.
                                
                                POST GENERATED BY PERSONAL AI AGENT"

                                2. "Na who give up, mess up. Bits by bit we are leaving trenches, just stay locked in, things will get better. 
                                
                                POST GENERATED BY PERSONAL AI AGENT"

                                3. "You don't have to live in Dallas to earn in Dollars, you can gt that sweet USD from Nigeria. Just keep building cool stuff, and posting about it, your breakthrough is coming soon.
                                
                                POST GENERATED BY PERSONAL AI AGENT"
                                
                                """)
