""" Module for daily post agent. """

import os
import requests
from dotenv import load_dotenv
from requests_oauthlib import OAuth1
from utils.openai import OpenAIClient

# Load environment variables
load_dotenv()

# Constants
X_ENDPOINT = "https://api.twitter.com/2/tweets"
X_API_KEY = os.getenv("X_API_KEY")
X_API_KEY_SECRET = os.getenv("X_API_KEY_SECRET")
X_ACCESS_TOKEN = os.getenv("X_ACCESS_TOKEN")
X_ACCESS_TOKEN_SECRET = os.getenv("X_ACCESS_TOKEN_SECRET")

# Validate environment variables
if not all([X_API_KEY, X_API_KEY_SECRET, X_ACCESS_TOKEN, X_ACCESS_TOKEN_SECRET]):
    raise ValueError("One or more X authentication tokens are not set in the environment variables.")

class DailyPostAgent:
    """ Agent for generating daily post."""

    def __init__(self):
        """Initializes the DailyPostAgent."""
        self.openai = OpenAIClient()
    
    def test_auth(self):
        """Tests authentication with the Twitter API."""
        url = "https://api.twitter.com/2/users/me"
        auth = OAuth1(
            X_API_KEY,
            client_secret=X_API_KEY_SECRET,
            resource_owner_key=X_ACCESS_TOKEN,
            resource_owner_secret=X_ACCESS_TOKEN_SECRET
        )
        response = requests.get(url, auth=auth)
        print(f"Test Status: {response.status_code}")
        print(f"Test Response: {response.text}")
        print(f"Request Headers: {response.request.headers}")
        return response.status_code == 200

    def post_on_twitter(self, post: str) -> None:
        """Posts the generated post on Twitter.

        Args:
            post (str): The generated post.
        """

        payload = {
            "text": post,
            "for_super_followers_only": False,
        }

        # Set up OAuth 1.0a authentication
        auth = OAuth1(
            X_API_KEY,
            client_secret=X_API_KEY_SECRET,
            resource_owner_key=X_ACCESS_TOKEN,
            resource_owner_secret=X_ACCESS_TOKEN_SECRET
        )

        headers = {
            "Content-Type": "application/json",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
        }

        response = requests.post(X_ENDPOINT, json=payload, headers=headers, auth=auth)

        if response.status_code != 201:
            raise ValueError(f"Failed to post on Twitter: {response.status_code} - {response.text}")
        else:
            print("Tweet posted successfully!")


    def generate_post(self) -> str:
        """Generates a daily post for software developers in Nigeria.

        Returns:
            str: The generated daily post.
        """
        return self.openai.chat("""
                                Your task is to write a short motivational post for software developers in Nigeria. Under "280 characters". Suitable for Twitter.
                                It must end with a call to action.
                                Don't be overly excited about the topic, but be enthusiastic about the subject.
                                Don't be too formal, but be friendly.
                                Don't use figures of speech.
                                Use active voice.
                                Use a bit of Nigeria pidgin English.
                                Write in the first person. Use the story telling technique implored in the examples below.

                                Example:
                                1. "Hey Naija dev, I know things are tough, I know you are tired of Garri and unreliable power supply, but remember things go soft very soon.
                                
                                POST GENERATED BY PERSONAL AI AGENT"

                                2. "Na who give up, mess up. Bits by bit we are leaving trenches, just stay locked in, things will get better. 
                                
                                POST GENERATED BY PERSONAL AI AGENT"

                                3. "You don't have to live in Dallas to earn in Dollars, you can gt that sweet USD from Nigeria. Just keep building cool stuff, and posting about it, your breakthrough is coming soon.
                                
                                POST GENERATED BY PERSONAL AI AGENT"
                                
                                """)
